### ISSUE TITLE
Missing dependency rexml?

### ISSUE THREAD

**Issue by jalyna** [yolk/valvat#117]
Hello! Thanks for the great work. It seems that in the latest release the dependency `rexml ` is missing:

```
remote:  !     Could not detect rake tasks        
remote:  !     ensure you can run `$ bundle exec rake -P` against your app        
remote:  !     and using the production group of your Gemfile.        
remote:  !     rake aborted!        
remote:  !     LoadError: cannot load such file -- rexml        
remote:  !     /tmp/build_7fa4b239/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'        
remote:  !     /tmp/build_7fa4b239/vendor/bundle/ruby/3.1.0/gems/valvat-1.2.0/lib/valvat/lookup/vies.rb:6:in `<main>'
```

**Comment by yolk** [comment]
Just released v1.2.1 with rexml as dependency added.

Dankeschön!
